trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:

- name: solution
  value: '**/*.sln'

- name: buildPlatform
  value: 'Any CPU'

- name: buildConfiguration
  value: 'Release'

#this variable is necessary to allow the agent to give access to the agent to the NuGet packages.
- name: NUGET_PACKAGES
  value: $(Agent.TempDirectory)/.nuget/packages

steps:

# ---------------------------------------------------------
# Restore
# ---------------------------------------------------------
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: '$(solution)'

# ---------------------------------------------------------
# Build
# ---------------------------------------------------------
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

# ---------------------------------------------------------
# Test + Coverage
# ---------------------------------------------------------
- script: |
    dotnet test SampleAppApi.sln --configuration Release --collect:"XPlat Code Coverage"
  displayName: Run tests with coverage

# ---------------------------------------------------------
# Publish coverage
# ---------------------------------------------------------
- task: PublishCodeCoverageResults@1
  displayName: Publish coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    reportDirectory: '$(Agent.TempDirectory)'

# ---------------------------------------------------------
# Build Docker image
# ---------------------------------------------------------
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    Dockerfile: Dockerfile
    repository: $(DOCKERHUB_USERNAME)/sampleappapi
    tags: |
      latest

- script: |
    echo "$(DOCKERHUB_TOKEN)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: Docker Hub Login

# ---------------------------------------------------------
# Push Docker image
# ---------------------------------------------------------
- script: |
    docker push $(DOCKERHUB_USERNAME)/sampleappapi:latest
  displayName: Push Docker image

# ---------------------------------------------------------
# Update ACA image
# ---------------------------------------------------------
- task: AzureCLI@2
  displayName: Update ACA image
  inputs:
    #we reuse the same service connection as in SampleDataAccessApi because it is only to login into Azure
    azureSubscription: 'SampleDataAccessApi_ServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp update \
        --name sampleappapi \
        --resource-group SampleAppApi_rg \
        --image docker.io/$(DOCKERHUB_USERNAME)/sampleappapi:latest
